export const RECEIVE_POSTS = 'RECEIVE_POSTS'
export const VOTE_POST = 'VOTE_POST'
export const RECEIVE_POSTS_BY_CATEGORY = 'RECEIVE_POSTS_BY_CATEGORY'
export const RECEIVE_POST = 'RECEIVE_POST'

export const RECEIVE_COMMENTARIES_BY_POST = 'RECEIVE_COMMENTARIES_BY_POST'
export const VOTE_COMMENT = 'VOTE_COMMENT'

export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES'